name: Deploy
on:
  workflow_call:
    secrets:
      VERCEL_TOKEN:
        required: true
    inputs:
      artifact-name:
        description: 'The name of the deployable artifact to download'
        required: true
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -lrt
      - name: Deploy
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod -y