name: Website Deployment
on: [push, workflow_dispatch]
jobs:
  lint:
    uses: ./.github/workflows/lint-workflow.yml
  test:
    needs: lint
    uses: ./.github/workflows/test-workflow.yml
  build:
    needs: test
    uses: ./.github/workflows/build-workflow.yml
  deploy:
    needs: build
    uses: ./.github/workflows/deploy-workflow.yml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    with:
      artifact-name: dist-files
  report:
    needs: [lint, deploy]
    if: failure()
    uses: ./.github/workflows/report-workflow.yml